// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TextFileReader.Data;

namespace TextFileReader.Migrations
{
    [DbContext(typeof(FileReaderContext))]
    [Migration("20190516125214_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TextFileReader.Data.Archivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNumber");

                    b.Property<int>("EmployeeQuantity");

                    b.Property<string>("FileName");

                    b.Property<DateTime>("PaymentDate");

                    b.Property<DateTime>("ProccesingDate");

                    b.Property<string>("RNC");

                    b.Property<decimal>("Roster");

                    b.Property<DateTime>("TransmissionDate");

                    b.HasKey("Id");

                    b.ToTable("Archivos");
                });

            modelBuilder.Entity("TextFileReader.Data.DetalleArchivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNumber");

                    b.Property<int>("ArchivoId");

                    b.Property<string>("EmployeeCode");

                    b.Property<string>("Identification");

                    b.Property<decimal>("Salary");

                    b.HasKey("Id");

                    b.HasIndex("ArchivoId");

                    b.ToTable("DetalleArchivos");
                });

            modelBuilder.Entity("TextFileReader.Data.DetalleArchivo", b =>
                {
                    b.HasOne("TextFileReader.Data.Archivo", "Archivo")
                        .WithMany("FileDetail")
                        .HasForeignKey("ArchivoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
