// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TextFileGeneration.Data;

namespace TextFileGeneration.Migrations
{
    [DbContext(typeof(FileGenerationContext))]
    [Migration("20190530003626_AddedInterExchangeEntity")]
    partial class AddedInterExchangeEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TextFileGeneration.Entities.Employee", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountNumber");

                    b.Property<decimal>("CotizableSalary");

                    b.Property<string>("EmployeeCode");

                    b.Property<decimal>("ISRSalary");

                    b.Property<string>("Identification");

                    b.Property<decimal>("InfotepSalary");

                    b.Property<int>("InstitutionId");

                    b.Property<decimal>("OtherRemuneration");

                    b.Property<double>("Salary");

                    b.Property<decimal>("VoluntaryAport");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TextFileGeneration.Entities.HardwareStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FileType");

                    b.Property<DateTime>("Period");

                    b.Property<string>("RNC");

                    b.Property<int>("TotalTransactions");

                    b.Property<DateTime>("TransmitionDate");

                    b.HasKey("Id");

                    b.ToTable("HardwareStores");
                });

            modelBuilder.Entity("TextFileGeneration.Entities.HardwareStoreEmployee", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("HardwareStoreId");

                    b.Property<double>("InfotepSalay");

                    b.Property<double>("IsrSalary");

                    b.Property<double>("OthersRemunerations");

                    b.Property<double>("Salary");

                    b.Property<double>("VoluntaryContribution");

                    b.HasKey("Id");

                    b.HasIndex("HardwareStoreId");

                    b.ToTable("HardwareStoreEmployees");
                });

            modelBuilder.Entity("TextFileGeneration.Entities.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountNumber");

                    b.Property<int>("EmployeesNumber");

                    b.Property<DateTime>("PaymentDate");

                    b.Property<string>("RNC");

                    b.Property<double>("TotalAmount");

                    b.Property<DateTime>("TransmitionDate");

                    b.HasKey("Id");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("TextFileGeneration.Entities.InterExchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreditsQuantity");

                    b.Property<DateTime>("Period");

                    b.Property<int>("StudentsQuantity");

                    b.Property<double>("TotalAmount");

                    b.Property<DateTime>("TransmissionDate");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("InterExchanges");
                });

            modelBuilder.Entity("TextFileGeneration.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<int>("CreditsQuantity");

                    b.Property<int>("CurrentStudentQuarter");

                    b.Property<string>("Identification");

                    b.Property<int?>("InterExchangeId");

                    b.Property<string>("RegistrationNumber");

                    b.HasKey("Id");

                    b.HasIndex("InterExchangeId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("TextFileGeneration.Entities.Employee", b =>
                {
                    b.HasOne("TextFileGeneration.Entities.Institution", "Institution")
                        .WithMany("Employees")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TextFileGeneration.Entities.HardwareStoreEmployee", b =>
                {
                    b.HasOne("TextFileGeneration.Entities.HardwareStore")
                        .WithMany("Employees")
                        .HasForeignKey("HardwareStoreId");
                });

            modelBuilder.Entity("TextFileGeneration.Entities.Student", b =>
                {
                    b.HasOne("TextFileGeneration.Entities.InterExchange")
                        .WithMany("Students")
                        .HasForeignKey("InterExchangeId");
                });
#pragma warning restore 612, 618
        }
    }
}
