// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TextFileGeneration.Data;

namespace TextFileGeneration.Migrations
{
    [DbContext(typeof(FileGenerationContext))]
    [Migration("20190518131756_Program2")]
    partial class Program2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TextFileGeneration.Entities.Employee", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountNumber");

                    b.Property<decimal>("CotizableSalary");

                    b.Property<string>("EmployeeCode");

                    b.Property<decimal>("ISRSalary");

                    b.Property<string>("Identification");

                    b.Property<decimal>("InfotepSalary");

                    b.Property<int>("InstitutionId");

                    b.Property<decimal>("OtherRemuneration");

                    b.Property<double>("Salary");

                    b.Property<decimal>("VoluntaryAport");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TextFileGeneration.Entities.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountNumber");

                    b.Property<int>("EmployeesNumber");

                    b.Property<DateTime>("PaymentDate");

                    b.Property<string>("RNC");

                    b.Property<double>("TotalAmount");

                    b.Property<DateTime>("TransmitionDate");

                    b.HasKey("Id");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("TextFileGeneration.Entities.Employee", b =>
                {
                    b.HasOne("TextFileGeneration.Entities.Institution", "Institution")
                        .WithMany("Employees")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
